apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  initContainers:
    - name: init1
      image: alpine
      args: ["sh","-c","sleep 15"]
    - name: init2
      image: alpine
      args: [ "sh","-c","sleep 10" ]
  containers:
    - name: c1
      image: nginx