apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  initContainers:
    - name: initc
      image: alpine
      args: ["sh","-c","sleep 25 && exit 1"]
  containers:
    - name: c1
      image: nginx