apiVersion: v1
kind: Pod
metadata:
  name: samplepod
spec:
  containers:
    - name: c1
      image: nginx
      readinessProbe:
        exec:
          command:
            - cat
            - /usr/share/nginx/html/index.html
        initialDelaySeconds: 50
        failureThreshold: 2
        periodSeconds: 10
