apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  ProjectName: "expense-app1"
  ProjectComponent: "frontend1"
  ProjectVersion: |
    This is Project - v4.0.0
    This is Project - V4.0.0
    This is Project - V4.0.0
  ProjectApp: |
    This is Project - nginx
    This is Project1 - nginx1

---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
   - name: c1
     image: nginx
     envFrom:
       - configMapRef:
           name: configmap1
     volumeMounts:
       - name: config-vol1
         mountPath: /tmp/config
  volumes:
    - name: config-vol1
      configMap:
        name: configmap1
