---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  ProjectName: "expense-app"
  ProjectComponent: "frontend"
  ProjectVersion: "v1.0.0"
  ProjectApp: "nginx"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: alpine
      env:
        - name: PARAMS
          value: "ProjectName ProjectComponent ProjectVersion ProjectApp"
      envFrom:
        - configMapRef:
            name: configmap1
      command: ["sh","-c"]
      args: ['for i in $PARAMS; do var="\$$i" ; [ -z `eval echo $var` ] && echo "variable is missing- $i" && exit 1 || echo "$i=$(eval echo $var)"']

          
            
