apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: alpine
      args: ["sh","-c","while true; do count=$((count+1)); echo Hello${count}-chaitu | tee -a /cache/index.html; sleep 5;done"]
      volumeMounts:
        - name: nginxvol
          mountPath: /cache
    - name: c2
      image: nginx
      volumeMounts:
        - name: nginxvol
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: nginxvol
      hostPath:
        path: /tmp/nginxvol