apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: alpine
      args: ["sh","-c","while true; do count=$((count+1)); echo Hello${count}-chaitu | tee -a /cache/index.html; sleep 5;done"]
      volumeMounts:
        - name: nginxvol
          mountPath: /cache
    - name: c2
      image: nginx
      volumeMounts:
        - name: nginxvol
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: nginxvol
      hostPath:
        path: /tmp/nginxvol
        type: # Directory optional

# type: Directory defines that the directory must already exist on the host, so you will have to create it there manually first, before using the hostpath.
# Other values for type are DirectoryOrCreate, File, FileOrCreate
# Where *OrCreate will be created dynamically if it doesn't already exist on the host.
