apiVersion: v1
kind: Pod
metadata:
  name: pod01
  labels:
    name: pod_anti_affinity
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: name
                operator: In
                values:
                - pod_anti_affinity
          topologyKey: "kubernetes.io/hostname"


  containers:
    - name: c1
      image: nginx

