#apiVersion: v1
#kind: Pod
#metadata:
#  name: pod01
#spec:
#  containers:
#    - name: c1
#      image: nginx
#  tolerations:
#    - key: app
#      value: nginx
#      operator: Equal
#      effect: NoSchedule

# ---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: pod01
#spec:
#  containers:
#    - name: c1
#      image: nginx
#  tolerations:
#    - operator: Exists
#      effect: NoSchedule

---
apiVersion: v1
kind: Pod
metadata:
  name: pod01
spec:
  nodeSelector:
    app: name
  containers:
    - name: c1
      image: nginx
  tolerations:
     - operator: Exists
       effect: NoSchedule
#     - operator: Exists
#       effect: NoExecute