apiVersion: v1
kind: Pod
metadata:
  name: pod01
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
           - matchExpressions:
               - key: node
                 operator: NotIn
                 values:
                   - worker1
  containers:
    - name: c1
      image: ngclearinx

---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: pod01
#spec:
#  affinity:
#    nodeAffinity:
#      preferredDuringSchedulingIgnoredDuringExecution:
#        - weight: 1
#          preference:
#            matchExpressions:
#               - key: node
#                 operator: NotIn
#                 values:
#                   - worker1
#  containers:
#    - name: c1
#      image: nginx

