q#apiVersion: v1
#kind: Pod
#metadata:
#  name: pod1
#spec:
#  containers:
#    - name: c1
#      image: nginx
#      volumeMounts:
#        - name: empty-volume
#          mountPath: /emptyVol
#        - name: empty-volume         # Two volumes have same data & one volume
#          mountPath: /emptyVol1
#  volumes:
#    - name: empty-volume
#      emptyDir: {}

##/var/lib/kubelet/pods/{podid}/volumes/kubernetes.io~empty-dir/
# ----------------------
# example -2
#-----------------------

apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: nginx
      volumeMounts:
        - name: empty-volume1
          mountPath: /emptyVol1
        - name: empty-volume2
          mountPath: /emptyVol2
  volumes:
    - name: empty-volume1
      emptyDir: {}
    - name: empty-volume2
      emptyDir: {}


---

# ---------------------------------
# Example-3
#----------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: nginx
      volumeMounts:
        - name: empty-volume
          mountPath: /usr/share/nginx/html/
    - name: c2
      image: alpine
      args:
        - "sh"
        - "-c"
        - "while true; do count=$((count+1));echo Hello${count}-Chaithanya | tee -a /emptyVol/index.html;sleep 5;done"
      volumeMounts:
      - name: empty-volume
        mountPath: /emptyVol
  volumes:
    - name: empty-volume
      emptyDir: {}