apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: nginx
      volumeMounts:
        - name: empty-volume
          mountPath: /emptyVol
        - name: empty-volume
          mountPath: /emptyVol1
  volumes:
    - name: empty-volume
      emptyDir: {}
