apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    component: frontend
spec:
  containers:
    - name: c1
      image: chaitu1812/expense-frontend
      ports:
        - containerPort: 80
          name: frontend
      env:
        - name: backend_ip
          value: "localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selectors:
    component: frontend
  type: NodePort
  ports:
    - port: 80
      name: frontend
